services:
  aux:
    build: .
    restart: always
    environment:
      VERSION: "0.1.0"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "eu-west-1"
    ports:
      - 8081:8081
